import { mkdir, writeFile } from "node:fs/promises";
import { collect, summarize } from "./collector.js";
import { collectMachines, dedupe } from "./aggregator.js";

const root = new URL("..", import.meta.url).pathname;
const out = `${root}data/scan.json`;
const command = process.argv[2] ?? "aggregate";
if (!["scan", "analyze", "aggregate"].includes(command)) throw new Error(`Unknown command: ${command}`);
const config = { server: { sessionsDir: process.env.PI_SERVER_SESSIONS ?? `${process.env.HOME}/.pi/agent/sessions` } };
if (process.env.PI_DESKTOP_SESSIONS) config.desktop = { sessionsDir: process.env.PI_DESKTOP_SESSIONS };
if (process.env.PI_LAPTOP_SESSIONS) config.laptop = { sessionsDir: process.env.PI_LAPTOP_SESSIONS };
if (process.env.PI_DESKTOP_HOST) config.desktop = { host: process.env.PI_DESKTOP_HOST };
if (process.env.PI_LAPTOP_HOST) config.laptop = { host: process.env.PI_LAPTOP_HOST };
const machineResults = command === "aggregate" ? await collectMachines(config) : [{ machine: process.env.PI_MACHINE ?? "server", ok: true, sessions: await collect({ machine: process.env.PI_MACHINE ?? "server" }) }];
const sessions = dedupe(machineResults);
const result = { schemaVersion: 1, generatedAt: new Date().toISOString(), machines: machineResults.map(({ sessions: _, ...m }) => m), sessions, summary: summarize(sessions) };
await mkdir(`${root}data`, { recursive: true });
await writeFile(out, JSON.stringify(result, null, 2) + "\n");
console.log(`Scanned ${sessions.length} sessions → ${out}`);
console.log(JSON.stringify(result.summary, null, 2));
